version: '3.4'

services:
  caffshop.es:
    environment:
      - discovery.type=single-node
    volumes:
      - animation_webshop_es_data:/user/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - animation_webshop_network

  caffshop.kibana:
    environment:
      - ELASTICSEARCH_URL=http://caffshop.es:9200
      - ELASTICSEARCH_HOSTS=http://caffshop.es:9200
    ports:
      - "5601:5601"
    networks:
      - animation_webshop_network
    depends_on:
      - caffshop.es

networks:
  animation_webshop_network:

volumes:
  animation_webshop_es_data: 
  animation_webshop_mssql_data: